---
- name: Create file1
  copy:
   dest: /home/secret/file3.txt
   content:
    Text Line1, in file1
    English hello
    Text Line3, {{ mytext }}


- name: Create file2
  copy:
   dest: /home/secret/file4.txt
   content:
    Text Line1, in file2
    english
    Text Line3, {{ mytext }}

