---

 - name: Loops Playbook
   hosts: staging_servers
   become: yes


   tasks:
   - name: Say Hello to All
     debug: msg="Hello {{ item }}"
     loop:
      - "Vasya"
      - "ilia"
      - "Duda"

   - name: Loop Until Example
     shell: echo -n Z >> myfile.txt && cat myfile.txt
     register: output
     delay: 2
     retries: 10
     until: output.stdout.find("ZZZZ") == false

   - name: Print Output
     debug:
       var: output.stdout


#   - name: Install many packaged
#     apt: name={{ item }} state=present
#     loop:
#      - apache2
#      - tree
#      - phyton
